version: "3.9"
services:
  # lnd_rest_client:
  #   build:
  #     context: .
  #     dockerfile: DockerfileRestClient
  #   container_name: lnd_rest_client
  #   image: mbio16/lnd_rest_client-image 
  #   volumes:
  #     - .env_mock:/app/.env:ro
  #     - ./certificate:/app/certificate:ro
  #   networks: 
  #     - backend
  #   depends_on:
  #     - "postgres"
  #     - "signal-client"
      
  lnd_websocket_client:
    build:
      context: .
      dockerfile: DockerfileWebsocketClient
    container_name: lnd_websocket_client
    image: mbio16/lnd_websocket_client
    restart: always
    volumes:
      - .env_mock:/app/.env:ro
      - ./certificate:/app/certificate:ro
    networks: 
      - backend
    depends_on:
      - "postgres"

  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: lnd_bot-db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: lnd_routing
    volumes: 
          - db:/var/lib/postgresql/data
    networks: 
      - backend

  signal-client:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: lnd_bot-signal_client
    restart: always
    environment:
      - MODE=normal
    volumes:
      - signal-config:/home/.local/share/signal-cli  
    networks:
      - backend
volumes:
  db:
    driver: local
  signal-config:
    driver: local

networks:
  backend:
    driver: bridge